name: Dinit on alpine-latest-armv6 CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  Alpine-latest-armv6_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: uraimo/run-on-arch-action@v2.3.0
      name: Getting depends & build & unit tests & integration tests
      with:
        arch: armv6
        distro: alpine_latest
        run: |
          apk add ncurses
          echo "$(tput bold) Getting depends:$(tput sgr0) apk update && apk add make g++ m4 file"
          apk update
          apk add make g++ m4 file
          echo "$(tput bold) Print g++ arch:$(tput sgr0) g++ -dumpmachine"
          g++ -dumpmachine
          echo "$(tput bold) Build:$(tput sgr0) make"
          make
          echo "$(tput bold) Print dinit executive file architecture:$(tput sgr0) file ./src/dinit"
          file ./src/dinit
          export LSAN_OPTIONS=verbosity=1:log_threads=1
          echo "$(tput bold) Unit tests:$(tput sgr0) make check"
          make check
          echo "$(tput bold) Integration tests:$(tput sgr0) make check-igr"
          make check-igr
