name: Dinit on debian-bullseye-i386 CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Debian-bullseye-i386_build:

    runs-on: ubuntu-latest
    container:
      image: debian:bullseye

    steps:
    - uses: actions/checkout@v3
    - name: Add 32-bit repos
      run: dpkg --add-architecture i386
    - name: Getting depends
      run: apt-get update && apt-get install gcc:i386 make:i386 m4:i386 g++:i386 -y
    - name: Print g++ architecture
      run: g++ -dumpmachine
    - name: chmod +x configure
      run: chmod +x ./configs/mconfig.Linux.sh
    - name: configure
      run: ./configs/mconfig.Linux.sh
    - name: Build
      run: make
    - name: Install "file" package via apt-get
      run: apt-get install file -y
    - name: Print dinit exec architecture
      run: file ./src/dinit
    - name: Unit tests
      run: make check
    - name: Integration tests
      run: make check-igr
